### PR TITLE
feat: RBR using Qdrant

### LINKED ISSUE #9: Add Qdrant vector store support
Hey all 👋.

I wanted to know if I can contribute a feature to add Qdrant - https://qdrant.tech/ as a supported vector store in the project.

### PR DESCRIPTION
**Pull request by Anush008**
Resolves #9.

I've refactored the keyword trigger implementation.

### CODE REVIEW

**Comment by Anush008** [comment]
Hey @recchris. Just bumping this PR.
Please take a look when possible.

**Comment by recchris** [comment]
> Hey @recchris. Just bumping this PR. Please take a look when possible.

Thanks @Anush008, taking a look!

**Comment by Anush008** [comment]
Hey @recchris.
Did you get a chance to look at this?

**Comment by recchris** [comment]
Hey @Anush008! Do you mind adding a test rq? You can see some existing tests in the/tests folder. Rest looks pretty good.

**Comment by Anush008** [comment]
Will do.

**Comment by Anush008** [comment]
Hi @recchris. I have added the tests and applied some misc. lint fixes throughout the project.

**Review by recchris — APPROVED** [review]

**Pull request merged**
